services:
  hardcore-plus:
    build: .
    image: hardcore-plus:latest
    container_name: hardcore_plus
    ports:
      - "8501:8501"
    volumes:
      - ./src/config.yaml:/app/config.yaml   
    env_file:
      - .env                             
    restart: unless-stopped