

server:
  url: "https://www.powerupstack.com/panel/instances/damagepart/console"
  files_url: "https://www.powerupstack.com/panel/instances/damagepart/files"
  terminal_selector: ".xterm-rows"

hardcore_plus:
  world_folder: "world"
  death_keywords:
    - "died"
    - "slain"
    - "shot by"
    - "burned to death"
    - "drowned"
    - "fell from a high place"
    - "blown up"
    - "tried to swim"
    - "hit the ground"
    - "withered away"  
  max_logs: 100

auth:
  login_url: "https://www.powerupstack.com/auth/login"
  panel_url: "https://www.powerupstack.com/panel/instances"