# config.yaml


server:
  # The main console URL
  url: "https://www.powerupstack.com/panel/instances/damagepart/console"
  # The file manager URL for deleting worlds
  files_url: "https://www.powerupstack.com/panel/instances/damagepart/files"
  # Selector for the terminal (standard for PowerupStack)
  terminal_selector: ".xterm-rows"

hardcore_plus:
  # The name of the world folder to delete
  world_folder: "world"
  # Keywords that trigger the reset
  death_keywords: ["died", "slain", "shot by","burned to death","drowned","fell from a high place","blown up","tried to swim", "hit the ground","withered away"]
  max_logs: 100